APP_PORT: 5000
BASE_URL_PATH: "/cart-order-service"
DB_SSL_MODE: "disable"
DB_USER: postgres
DB_HOST: localhost
DB_PASSWORD: postgres
DB_NAME: shopeefun-cart-order-service
DB_DEBUG: true
DB_PORT: 5432